2025-06-14 18:18:00,024 INFO    MainThread:1569548 [wandb_setup.py:_flush():81] Current SDK version is 0.20.1
2025-06-14 18:18:00,024 INFO    MainThread:1569548 [wandb_setup.py:_flush():81] Configure stats pid to 1569548
2025-06-14 18:18:00,024 INFO    MainThread:1569548 [wandb_setup.py:_flush():81] Loading settings from /data/satori_hdd1/mutyuu/.config/wandb/settings
2025-06-14 18:18:00,025 INFO    MainThread:1569548 [wandb_setup.py:_flush():81] Loading settings from /data/satori_hdd1/mutyuu/workspace/LLM_A2Z/example_wandb/wandb/settings
2025-06-14 18:18:00,025 INFO    MainThread:1569548 [wandb_setup.py:_flush():81] Loading settings from environment variables
2025-06-14 18:18:00,025 INFO    MainThread:1569548 [wandb_init.py:setup_run_log_directory():703] Logging user logs to /data/satori_hdd1/mutyuu/workspace/LLM_A2Z/example_wandb/wandb/run-20250614_181800-ayscus40/logs/debug.log
2025-06-14 18:18:00,025 INFO    MainThread:1569548 [wandb_init.py:setup_run_log_directory():704] Logging internal logs to /data/satori_hdd1/mutyuu/workspace/LLM_A2Z/example_wandb/wandb/run-20250614_181800-ayscus40/logs/debug-internal.log
2025-06-14 18:18:00,025 INFO    MainThread:1569548 [wandb_init.py:init():831] calling init triggers
2025-06-14 18:18:00,025 INFO    MainThread:1569548 [wandb_init.py:init():836] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-06-14 18:18:00,025 INFO    MainThread:1569548 [wandb_init.py:init():872] starting backend
2025-06-14 18:18:00,241 INFO    MainThread:1569548 [wandb_init.py:init():875] sending inform_init request
2025-06-14 18:18:00,250 INFO    MainThread:1569548 [wandb_init.py:init():883] backend started and connected
2025-06-14 18:18:00,252 INFO    MainThread:1569548 [wandb_init.py:init():956] updated telemetry
2025-06-14 18:18:00,261 INFO    MainThread:1569548 [wandb_init.py:init():980] communicating run to backend with 300.0 second timeout
2025-06-14 18:18:12,598 WARNING MainThread:1569548 [wandb_init.py:init():1613] [no run ID] interrupted
Traceback (most recent call last):
  File "/data/satori_hdd1/mutyuu/miniconda3/envs/trl/lib/python3.13/site-packages/wandb/sdk/wandb_init.py", line 1609, in init
    return wi.init(run_settings, run_config, run_printer)
           ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/satori_hdd1/mutyuu/miniconda3/envs/trl/lib/python3.13/site-packages/wandb/sdk/wandb_init.py", line 999, in init
    result = wait_with_progress(
        run_init_handle,
    ...<2 lines>...
        display_progress=display_init_message,
    )
  File "/data/satori_hdd1/mutyuu/miniconda3/envs/trl/lib/python3.13/site-packages/wandb/sdk/mailbox/wait_with_progress.py", line 24, in wait_with_progress
    return wait_all_with_progress(
           ~~~~~~~~~~~~~~~~~~~~~~^
        [handle],
        ^^^^^^^^^
    ...<2 lines>...
        display_progress=display_progress,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )[0]
    ^
  File "/data/satori_hdd1/mutyuu/miniconda3/envs/trl/lib/python3.13/site-packages/wandb/sdk/mailbox/wait_with_progress.py", line 87, in wait_all_with_progress
    return asyncio_compat.run(progress_loop_with_timeout)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/satori_hdd1/mutyuu/miniconda3/envs/trl/lib/python3.13/site-packages/wandb/sdk/lib/asyncio_compat.py", line 30, in run
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/data/satori_hdd1/mutyuu/miniconda3/envs/trl/lib/python3.13/concurrent/futures/_base.py", line 451, in result
    self._condition.wait(timeout)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/data/satori_hdd1/mutyuu/miniconda3/envs/trl/lib/python3.13/threading.py", line 359, in wait
    waiter.acquire()
    ~~~~~~~~~~~~~~^^
KeyboardInterrupt
2025-06-14 18:18:13,256 INFO    MsgRouterThr:1569548 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 2 handles.
